# Generated by Django 4.2.6 on 2023-11-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dawrni_app', '0011_category_client_company_companyphoto_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='company',
            name='category',
        ),
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.RemoveField(
            model_name='companyphoto',
            name='company',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyPhoto',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
