# Generated by Django 4.2.6 on 2023-11-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawrni_app', '0013_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='test_type',
            field=models.CharField(choices=[('company', 'Company'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
