# Generated by Django 4.2.6 on 2023-11-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dawrni_app', '0014_user_profile_image_user_test_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='test_type',
            new_name='user_type',
        ),
    ]
