# Generated by Django 4.2.6 on 2023-11-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawrni_app', '0018_custom_user_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='test',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='user_type',
            field=models.CharField(choices=[('company', 'Company'), ('user', 'User')], default='user', max_length=8),
        ),
    ]
