# Generated by Django 4.2.6 on 2023-11-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawrni_app', '0019_remove_custom_user_test_custom_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
