# Generated by Django 4.2.6 on 2023-11-12 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dawrni_app', '0021_alter_custom_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='About (English)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='Address (English)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dawrni_app.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (English)'),
        ),
    ]
