# Generated by Django 4.2.6 on 2023-11-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawrni_app', '0022_alter_company_about_en_alter_company_address_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('sports', 'Sports'), ('art', 'Art'), ('game', 'Game')], max_length=255),
        ),
    ]
