# Generated by Django 4.2.6 on 2023-11-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawrni_app', '0026_alter_custom_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
