# Generated by Django 4.2.6 on 2023-11-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawrni_app', '0027_alter_custom_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
