# Generated by Django 4.2.6 on 2023-11-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawrni_app', '0029_alter_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
