# Generated by Django 4.2.6 on 2023-11-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawrni_app', '0030_alter_client_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='company',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
