# Generated by Django 4.2.6 on 2023-11-23 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dawrni_app', '0031_company_lat_company_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dawrni_app.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dawrni_app.company')),
            ],
            options={
                'unique_together': {('client', 'company')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', through='dawrni_app.Favorite', to='dawrni_app.company'),
        ),
    ]
