# Generated by Django 4.2.6 on 2023-12-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawrni_app', '0033_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Is Favorite'),
        ),
    ]
